### ISSUE TITLE
உலகை குலுக்கிய பத்து நாட்கள் - ஜான் ரீடு

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Proofread-Works#1]
https://archive.org/download/russia_books_tamil/%E0%AE%89%E0%AE%B2%E0%AE%95%E0%AF%88%20%E0%AE%95%E0%AF%81%E0%AE%B2%E0%AF%81%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%AF%20%E0%AE%AA%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AF%81%20%E0%AE%A8%E0%AE%BE%E0%AE%9F%E0%AF%8D%E0%AE%95%E0%AE%B3%E0%AF%8D.pdf

**Comment by tshrinivasan** [comment]
[all_text_for_10_days.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3244407/all_text_for_10_days.pdf.txt)

@Tharagavaskar மெய்ப்பு பார்க்கவும்.

**Comment by Tharagavaskar** [comment]
[0706.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3265684/0706.docx)

**Comment by Tharagavaskar** [comment]
200 pages completed

**Comment by Tharagavaskar** [comment]
260 pages completed till now

**Comment by Tharagavaskar** [comment]
330/654 pages completed

**Comment by Tharagavaskar** [comment]
400/654 pages completed

**Comment by gnuanwar** [comment]
@Tharagavaskar  open this issue

**Comment by Tharagavaskar** [comment]
471/654 pages completed

**Comment by Tharagavaskar** [comment]
550/654 pages completed today

**Comment by Tharagavaskar** [comment]
[உலகை குலுக்கிய பத்து நாட்கள்.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3326382/default.docx)

finished

**Comment by gnuanwar** [comment]
Thanks

**Comment by gnuanwar** [comment]
@Tharagavaskar add any formatting issues here
