### ISSUE TITLE
ஆதிவாசி மறைந்த வரலாறு

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Proofread-Works#13]
இந்த நூலை மெய்ப்பு பார்க்கவும் 

http://tamildigitallibrary.in/book-detail.php?id=jZY9lup2kZl6TuXGlZQdjZt8kux0&tag=%E0%AE%86%E0%AE%A4%E0%AE%BF%E0%AE%B5%E0%AE%BE%E0%AE%9A%E0%AE%BF%E0%AE%95%E0%AE%B3%E0%AE%BF%E0%AE%A9%E0%AF%8D%20%E0%AE%AE%E0%AE%B1%E0%AF%88%E0%AE%A8%E0%AF%8D%E0%AE%A4%20%E0%AE%B5%E0%AE%B0%E0%AE%B2%E0%AE%BE%E0%AE%B1%E0%AF%81#book1/

[new advasigalin maraithavaralaru proofing current.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3262681/new.advasigalin.maraithavaralaru.proofing.current.docx)

**Comment by Tharagavaskar** [comment]
110 /156 pages completed today

**Comment by Tharagavaskar** [comment]
[new.advasigalin.maraithavaralaru.proofing.current.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3295269/new.advasigalin.maraithavaralaru.proofing.current.docx)

finished
