### ISSUE TITLE
கேரள ஆதிவாசி

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Proofread-Works#14]
இந்த நூலை மெய்ப்பு பாரக்கவும்

[new kerela advasigal.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3262708/new.kerela.advasigal.pdf)

[kerela adivasiaglfull .docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3262715/kerela.adivasiaglfull.docx)

**Comment by gnuanwar** [comment]
[rotated.kerela.advasigal-1.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3328968/rotated.kerela.advasigal-1.pdf)

hek this file @Tharagavaskar

**Comment by Tharagavaskar** [comment]
thank you sir

With Greetings,
Thara

**Comment by Tharagavaskar** [comment]
[kerela.adivasiaglfull.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3330281/kerela.adivasiaglfull.docx)

finished 100/100 pages

**Comment by gnuanwar** [comment]
Thanks

**Comment by gnuanwar** [comment]
[kerela.adivasiaglfull_pic_added .docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3351042/kerela.adivasiaglfull_pic_added.docx)


pictures added from source
