### ISSUE TITLE
யார் இந்த நாடோடிகள் 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Proofread-Works#16]
[yarindha nadodigal.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3268331/yarindha.nadodigal.pdf)

[yaruindha nadodigal.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3343170/yaruindha.nadodigal.docx)

@Tharagavaskar do proof read

**Comment by gnuanwar** [comment]
@tshrinivasan wrong file has been uploaded before

@Tharagavaskar now it is orrected do proof read

**Comment by gnuanwar** [comment]
@Tharagavaskar delete the empty pages before proof read

**Comment by Tharagavaskar** [comment]
Okay sir
