### ISSUE TITLE
யூதர்கள் ஆதிவாசிகளானது  எப்படி? 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Proofread-Works#22]
[udarargal.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3314568/udarargal.pdf)
[udarargal.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3314569/udarargal.docx)

@Tharagavaskar

**Comment by Tharagavaskar** [comment]
actual content shows in pdf 94 pages.. but in document file have only 80 pages out of 94 pages.. pls. upload balance pages

**Comment by gnuanwar** [comment]
@Tharagavaskar corrected file
[new_udarargal.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3333954/new_udarargal.docx)

**Comment by Tharagavaskar** [comment]
@Anwar Latiff <gnuanwar@gmail.com>

**Comment by Tharagavaskar** [comment]
[udarargal.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3334660/udarargal.docx)

finished 94/94 pages
