### ISSUE TITLE
மார்க்சிய அழகியல் - ஞானி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Proofread-Works#24]
https://archive.org/download/marxia-azhagiyal/marxia-azhagiyal.pdf

**Comment by Tharagavaskar** [comment]
upload docx file

**Comment by gnuanwar** [comment]
Copied

**Comment by gnuanwar** [comment]
[marxia-azhagiyalfull.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3344545/marxia-azhagiyalfull.docx)
@Tharagavaskar ocr ouput

**Comment by Tharagavaskar** [comment]
60/188 pages completed

**Comment by Tharagavaskar** [comment]
130/188 pages completed

**Comment by Tharagavaskar** [comment]
[மார்க்சிய அழகியல்.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3430151/default.docx)

**Comment by gurulenin** [comment]
http://freetamilebooks.com/ebooks/marxia_azhagiyal/


வெளியிடப்பட்டது.
