### ISSUE TITLE
எழுத்து நாடகம் சினிமா சோதனைகளும் சாதனைகளும் எஸ் சாமிநாதன் 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Proofread-Works#33]
[all_text_for_TM34735.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3489899/all_text_for_TM34735.pdf.txt)
[TM34734.pdf](https://github.com/KaniyamFoundation/Proofread-Works/files/3489778/TM34734.pdf)

காப்புரிமை CC-BY-SA

**Comment by gnuanwar** [comment]
ocr result posted @Tharagavaskar  proof read

**Comment by Tharagavaskar** [comment]
100/178 pages completed
