### ISSUE TITLE
இராவண காவியம்- குழந்தை 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/Proofread-Works#36]
@Tharagavaskar proof read

[all_text_for_இராவண_காவியம்.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3521680/all_text_for_._.pdf.txt)

**Comment by tshrinivasan** [comment]
Don't proofread this.

We have text for this book from tamilmunn publishers.

**Comment by gnuanwar** [comment]
Copied
