### ISSUE TITLE
பொதுக்கல்வி - லெனின்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Proofread-Works#4]
https://archive.org/download/russia_books_tamil/%E0%AE%B2%E0%AF%86%E0%AE%A9%E0%AE%BF%E0%AE%A9%E0%AF%8D%20%E0%AE%AA%E0%AF%8A%E0%AE%A4%E0%AF%81%E0%AE%95%E0%AE%B2%E0%AF%8D%E0%AE%B5%E0%AE%BF.pdf

**Comment by tshrinivasan** [comment]
[all_text_for_general_education_lenin.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3244641/all_text_for_general_education_lenin.pdf.txt)

@Tharagavaskar  Proofread this

**Comment by Tharagavaskar** [comment]
120/248 pages completed

**Comment by Tharagavaskar** [comment]
171/248 pages completed

**Comment by gnuanwar** [comment]
@Tharagavaskar update completed pages

**Comment by Tharagavaskar** [comment]
[லெனின்.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3348261/default.docx)
finished 248/248 pages
