### ISSUE TITLE
நமக்கான தமிழிலக்கியக் கொள்கை - கோவை ஞானி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Proofread-Works#40]
https://archive.org/download/namakkana-tamililakkia-kolgai-source/namakkana-tamililakkia-kolgai.pdf

**Comment by gnuanwar** [comment]
[all_text_for_namakkana-tamililakkia-kolgai.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3643307/all_text_for_namakkana-tamililakkia-kolgai.pdf.txt)

**Comment by Tharagavaskar** [comment]
Okay sir

**Comment by Tharagavaskar** [comment]
80/216 pages completed

**Comment by Tharagavaskar** [comment]
195/216 pages completed

**Comment by Tharagavaskar** [comment]
[நமக்கான தமிழிலக்கியக் கொள்கை.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3661182/default.docx)
216/216 pages finished

**Comment by gurulenin** [comment]
released here

https://freetamilebooks.com/ebooks/tamil_literature_policy/
