### ISSUE TITLE
ஞானியின் கவிதைகள் - ஞானி

### ISSUE THREAD

**Issue by gurulenin** [KaniyamFoundation/Proofread-Works#41]
https://archive.org/download/gnaniyin-kavidhaigal/gnaniyin-kavidhaigal.pdf

**Comment by Tharagavaskar** [comment]
pls. upload ocr

**Comment by gnuanwar** [comment]
[all_text_for_gnaniyin-kavidhaigal.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3690389/all_text_for_gnaniyin-kavidhaigal.pdf.txt)
ocr output

**Comment by Tharagavaskar** [comment]
50/300 pages completed

**Comment by Tharagavaskar** [comment]
90/300 pages completed

**Comment by Tharagavaskar** [comment]
140/300 pages completed

**Comment by Tharagavaskar** [comment]
230/300 pages completed

**Comment by Tharagavaskar** [comment]
ocr file has only 250 pages... pls upload balance 50 pages

**Comment by gnuanwar** [comment]
Copied

**Comment by gnuanwar** [comment]
[updated_all_text_for_gnaniyin-kavidhaigal.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3732671/updated_all_text_for_gnaniyin-kavidhaigal.pdf.txt)

@Tharagavaskar proof read again

**Comment by Tharagavaskar** [comment]
[ஞானியின் கவிதைகள்.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3734627/default.docx)
proof read finished
