### ISSUE TITLE
மார்க்சியமும் தமிழ் இலக்கியமும்  - கோவை ஞானி

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Proofread-Works#7]
PDF - 
https://archive.org/download/kovai_gnani_books_scanned/marx-tamil-literature.pdf

**Comment by tshrinivasan** [comment]
cover
https://archive.org/download/kovai_gnani_books_scanned/marx-tamil-literature.jpg

**Comment by tshrinivasan** [comment]
[all_text_for_marx-tamil-literature.pdf.txt](https://github.com/KaniyamFoundation/Proofread-Works/files/3244581/all_text_for_marx-tamil-literature.pdf.txt)

@Tharagavaskar proofread this.

**Comment by Tharagavaskar** [comment]
120 pages completed till now

**Comment by Tharagavaskar** [comment]
210 pages completed now

**Comment by Tharagavaskar** [comment]
300 pages completed as on date

**Comment by gnuanwar** [comment]
mention total book pages and leftover pages @Tharagavaskar

**Comment by Tharagavaskar** [comment]
[marx-tamil-literature.docx](https://github.com/KaniyamFoundation/Proofread-Works/files/3285803/marx-tamil-literature.docx)

finished the book 
மார்க்சியமும் தமிழ் இலக்கியமும்

**Comment by gnuanwar** [comment]
thanks

**Comment by Tharagavaskar** [comment]
Sir..I will start next book யார் இந்த நாடோடிகள் -பிலோ இருதயநாத்

**Comment by gnuanwar** [comment]
Ok congrats,thanks post the proof reading daily report by completed /total
pages

**Comment by Tharagavaskar** [comment]
Okay sir

**Comment by gnuanwar** [comment]
@Tharagavaskar if you finished proof reading mark the label proof read finished  if your starting new book for proof reading mark the label  proof red finished
